import { apiRequest } from "./api";
export type CampaignStatus = "queued" | "running" | "paused" | "cancelled" | "completed" | "failed";
export type QueueItem = { campaign_id:string; name:string; status:"queued"|"running"|"paused"|"failed"; attempts:number; available_at:string; locked_at?:string|null; updated_at:string; error?:string|null };
export type QueueMonitor = { queued:number; running:number; paused:number; failed:number; completed:number; attempts:number; items:QueueItem[]; activeCampaignId:string|null; workerRunning:boolean; maxWorkers:number };
export type Campaign = { id:string; name:string; type:string; instance:string; status:CampaignStatus; delayMs:number; payload:Record<string,unknown>; recipients:Array<Record<string,string>>; results:Array<{index:number;phone:string;ok:boolean;message?:string;deliveryStatuses?:unknown[]}>; total:number; sent:number; failed:number; createdAt:string; startedAt?:string|null; completedAt?:string|null; error?:string };

async function request<T>(path:string,init:RequestInit={}):Promise<T>{return apiRequest<T>(path,init);}
export const campaignsApi={list:()=>request<Campaign[]>("/api/campaign-jobs"),get:(id:string)=>request<Campaign>(`/api/campaign-jobs/${encodeURIComponent(id)}`),create:(p:Record<string,unknown>)=>request<Campaign>("/api/campaign-jobs",{method:"POST",body:JSON.stringify(p)}),pause:(id:string)=>request<Campaign>(`/api/campaign-jobs/${encodeURIComponent(id)}/pause`,{method:"POST"}),resume:(id:string)=>request<Campaign>(`/api/campaign-jobs/${encodeURIComponent(id)}/resume`,{method:"POST"}),cancel:(id:string)=>request<Campaign>(`/api/campaign-jobs/${encodeURIComponent(id)}/cancel`,{method:"POST"}),queue:()=>request<QueueMonitor>("/api/campaign-jobs/queue/status"),
retryFailed:(id:string)=>request<Campaign>(`/api/campaign-jobs/${encodeURIComponent(id)}/retry-failed`,{method:"POST"})};
