/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. It is kept in sync here so the repository
// remains runnable even before the next dev/build route generation pass.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads/$leadId'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const AppRoute = AppRouteImport.update({ id: '/_app', getParentRoute: () => rootRouteImport } as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({ id: '/analytics', path: '/analytics', getParentRoute: () => AppRoute } as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({ id: '/automations', path: '/automations', getParentRoute: () => AppRoute } as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({ id: '/campaigns', path: '/campaigns', getParentRoute: () => AppRoute } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AppRoute } as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({ id: '/permissions', path: '/permissions', getParentRoute: () => AppRoute } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AppRoute } as any)
const AppTeamRoute = AppTeamRouteImport.update({ id: '/team', path: '/team', getParentRoute: () => AppRoute } as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({ id: '/templates', path: '/templates', getParentRoute: () => AppRoute } as any)
const AppSessionsRoute = AppSessionsRouteImport.update({ id: '/sessions', path: '/sessions', getParentRoute: () => AppRoute } as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({ id: '/leads/', path: '/leads/', getParentRoute: () => AppRoute } as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({ id: '/leads/$leadId', path: '/leads/$leadId', getParentRoute: () => AppRoute } as any)

const AppRouteChildren = {
  AppAnalyticsRoute,
  AppAutomationsRoute,
  AppCampaignsRoute,
  AppDashboardRoute,
  AppPermissionsRoute,
  AppSettingsRoute,
  AppTeamRoute,
  AppTemplatesRoute,
  AppSessionsRoute,
  AppLeadsLeadIdRoute,
  AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)
const rootRouteChildren = { IndexRoute, TermsRoute, AppRoute: AppRouteWithChildren }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
